when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeSessionHandler