controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_commande:
    path: '/commande/{id}'
    controller: 'App\Controller\AccueilController::commande'
